### PR TITLE
Fix mlp nonlinearity

### PR DESCRIPTION
**Pull request by ziqi-ma**
Fix nonlinearity of final MLP - otherwise output is lower-bounded by GELU.

### CODE REVIEW

**Comment by JeanKossaifi** [comment]
Thanks @ziqi-ma! @m4e7 this fixes the issue you found too right?

**Comment by m4e7** [comment]
> Thanks @ziqi-ma! @m4e7 this fixes the issue you found too right?

Yeah, this fixes it! We should also fix `MLPLinear.forward()`, too: https://github.com/neuraloperator/neuraloperator/blob/a371d0890698eb2617dc805b527449b7acac8581/neuralop/layers/mlp.py#L77C34-L77C34

**Comment by JeanKossaifi** [comment]
@ziqi-ma would you be able to make that change too?

**Comment by JeanKossaifi** [comment]
I'll merge this @ziqi-ma as this is an important fix and opened #200 to track the other issue if you want to open a PR for it too! Thanks for your contribution!

**Pull request merged**
