### PR TITLE
Changed MLP to nn.Linear to allow 4D prediction

### PR DESCRIPTION
**Pull request by gegewen**
This PR changed the lifting and projection in FNO to allow 4D prediction

### CODE REVIEW

**Comment by JeanKossaifi** [comment]
Thanks @gegewen - I think we should directly modify the MLP to support 4D instead, do you agree?

**Comment by gegewen** [comment]
There is no Conv4D if we use MLP - are there any suggestions?

**Comment by JeanKossaifi** [comment]
Thanks @gegewen -- could we add the nested-fno in a separate PR? I want to merge your changes to support 4D MLP asap!

**Comment by gegewen** [comment]
Hey, sorry @JeanKossaifi, the nested no was automatically pushed here when I pushed it to my branch - do you want me to revert this one to without NestedFNO first?

**Comment by JeanKossaifi** [comment]
That would be great, thanks @gegewen! Looks like there is a conflict with the latest version as well.

**Pull request closed without merging**
