### PR TITLE
Deepcopy base model

### PR DESCRIPTION
**Pull request by dhpitt**
The models in `neuralop.models` subclass `neuralop.models.BaseModel`, which adds lots of useful functionality but does not implement the `__deepcopy__` method necessary to copy a torch module's architecture and state. This PR adds a method to do that.

### CODE REVIEW

**Comment by JeanKossaifi** [comment]
Wouldn't the default __deepcopy__ work out of the box?

**Comment by dhpitt** [comment]
> Wouldn't the default **deepcopy** work out of the box?
No, it throws an error - there's no way to access the internal module state from base_model by default.

**Review by JeanKossaifi — COMMENTED** [review]
I'm not sure I get why we need this? 

Also shouldn't we explicitly copy the arguments? From the [doc](https://docs.python.org/3/library/copy.html):

> If the __deepcopy__() implementation needs to make a deep copy of a component, it should call the [deepcopy()](https://docs.python.org/3/library/copy.html#copy.deepcopy) function with the component as first argument and the memo dictionary as second argument. The memo dictionary should be treated as an opaque object.

**Comment by JeanKossaifi** [comment]
Was this resolved @dhpitt ?

**Pull request closed without merging**
